const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())

let albums = {
    "supa dupa fly": {
        "title":"Supa Dupa Fly",
        "cover": "https://upload.wikimedia.org/wikipedia/en/d/df/Missy_Elliott_Supa_Dupa_Fly.jpg",
        "released":"1997-07-15",
        "studio":"Master Sound Studios",
        "length":"60:06",
        "label":["Goldmine","Elektra"],
        "producers":["Missy Elliott","Timbaland"],
        "tracks":[
            {"track":"01",
            "title": "Busta's Intro",
            "featuring":["Busta Rhymes"],
            "writers": ["Trevor Smith"],
            "producers":["Timbaland"],
                "length": "1:53",
            },
            {"track":"02",
            "title": "Hit Em wit da Hee",
            "featuring":["Lil' Kim"],
            "writers": ["Melissa Elliot","Timothy Mosley", "Kimberly Jones","Alcia Richards"],
            "producers":["Timbaland"],
            "length": "4:19",
            },
            {"track":"03",
            "title": "Sock It 2 Me",
            "featuring":["Da Brat"],
            "writers": ["Melissa Elliot","Timothy Mosley", "William Hart","Thom Bell","Shawntae Harris"],
            "producers":["Timbaland"],
            "length": "4:17",
             },
            {"track":"04",
            "title": "The Rain (Supa Dupa Fly)",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley", "Ann Peebles","Bernard Miller","Don Bryant"],
            "producers":["Timbaland"],
            "length": "4:11",
             },
            {"track":"05",
            "title": "Beep Me 911",
            "featuring":["702","Magoo"],
            "writers": ["Melissa Elliot","Timothy Mosley", "Melvin Barcliff"],
            "producers":["Timbaland"],
            "length": "4:57",
            },
            {"track":"06",
            "title": "They Don't Wanna Fuck wit Me",
            "featuring":["Timbaland"],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "3:18",
            },
            {"track":"07",
            "title": "Pass da Blunt",
            "featuring":["Timbaland"],
            "writers": ["Melissa Elliot","Timothy Mosley", "Jackie Mittoo","Lloyd Ferguson", "Felix HEadley Dennet", "Huffor Brown", "Robbie Lyn", "Leyroy Sibbles", "Fitzroy Simpson"],
            "producers":["Timbaland"],
            "length": "3:17",
             },
            {"track":"08",
            "title": "Bite Our Style (Interlude)",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "0:43",
            },
            {"track":"09",
            "title": "Friendlly Skies",
            "featuring":["Ginuwine"],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:59",
            },
            {"track":"10",
            "title": "Best Friends",
            "featuring":["Aaliyah"],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:07",
            },
            {"track":"11",
            "title": "Don't Be Commin'(In My Face)",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:11",
            },
            {"track":"12",
            "title": "Izzy Izzy Ahh",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "3:54",
            },
            {"track":"13",
            "title": "Why You Hurt Me",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley","Eddie Floyd"],
            "producers":["Timbaland"],
            "length": "4:31",
            },
            {"track":"14",
            "title": "I'm Talkin",
            "featuring":[],
            "writers": ["Melissa Elliot","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "5:02",
             },
            {"track":"15",
            "title": "Gettaway",
            "featuring":["Space","Nicole Wray"],
            "writers": ["Melissa Elliot","Timothy Mosley", "Tracey Selden","Lashone Siplin"],
            "producers":["Timbaland"],
            "length": "4:25",
            },
            {"track":"16",
            "title": "Busta's Outro",
            "featuring":["Busta Rhymes"],
            "writers": ["Trevor Smith","Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "1:38",
            },
            {"track":"17",
            "title": "Missy Finale",
            "featuring":[],
            "writers": ["Melissa Elliott",],
            "producers":["Timbaland"],
            "length": "0:24",
            }
        ]
        
    },
    "da real world":{
        "title":"Da Real World",
        "cover": "https://upload.wikimedia.org/wikipedia/en/d/de/Missy_Elliott_-_Da_Real_World_-_Album.jpg",
        "released":"1999-06-22",
        "studio":"Master Sound Studios",
        "length":"64:09",
        "label":["Goldmine","Elektra"],
        "producers":["Missy Elliott","Timbaland"],
        "tracks":[
            
            {"track":"01",
            "title": "Mysterious (Intro)",
            "featuring":[],
            "writers": [],
            "producers":["Timbaland"],
            "length": "1:07",
            },
            {"track":"02",
            "title": "Beat Biters",
            "featuring":[],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:24",
            },
            {"track":"03",
            "title": "Busa Rhyme",
            "featuring":["Eminem"],
            "writers": ["Melissa Elliott", "Timothy Mosley","Marsha Mathers","Rob Parissi"],
            "producers":["Timbaland"],
            "length": "5:01",
            },
            {"track":"04",
            "title": "All In My Grill",
            "featuring":["Big Boi","Nicole Wray"],
            "writers": ["Melissa Elliott", "Timothy Mosley","Antwan Patton"],
            "producers":["Timbaland"],
            "length": "4:44",
            },
            {"track":"05",
            "title": "Dangerous Mouths",
            "featuring":["Redman"],
            "writers": ["Melissa Elliott", "Timothy Mosley","Reggie Noble"],
            "producers":["Timbaland"],
            "length": "3:29",
            },
            {"track":"06",
            "title": "Hot Boyz",
            "featuring":[],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "3:26",
            },
            {"track":"07",
            "title": "You Don't Know",
            "featuring":["Lil' Mo"],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Cynthia Loving"],
            "producers":["Timbaland"],
            "length": "4:48",
            },
            {"track":"08",
            "title": "Mr D.J.",
            "featuring":["LAdy Saw"],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Marion Hall"],
            "producers":["Timbaland"],
            "length": "4:30",
            },
            {"track":"09",
            "title": "Checkin' for You (Interlude)",
            "featuring":["Lil' Kim"],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Kimberly Jones"],
            "producers":["Timbaland"],
            "length": "2:09",
            },
            {"track":"10",
            "title": "Stickin' Chickens",
            "featuring":["Aaliyah", "Da Brat"],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Shawntae Harris"],
            "producers":["Timbaland"],
            "length": "4:55",
            },
            {"track":"11",
            "title": "Smooth Chick",
            "featuring":[],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:18",
            },
            {"track":"12",
            "title": "We Did It",
            "featuring":[],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "3:51",
            },
            {"track":"13",
            "title": "Throw Your Hands Up (Interlude)",
            "featuring":["Lil' Kim"],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Kimberly Jones"],
            "producers":["Timbaland"],
            "length": "1:18",
            },
            {"track":"14",
            "title": "She's a Bitch",
            "featuring":[],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:00",
            },
            {"track":"15",
            "title": "U Can't Resist",
            "featuring":["Juvenile","B.G."],
            "writers": ["Melissa Elliott", "Timothy Mosley", "Terius Gray", "Christopher Dorsey"],
            "producers":["Timbaland"],
            "length": "4:37",
            },
            {"track":"16",
            "title": "Crazy Feelings",
            "featuring":["Beyonce"],
            "writers": ["Melissa Elliott", "Timothy Mosley"],
            "producers":["Timbaland"],
            "length": "4:34",
            },
            {"track":"17",
            "title": "Religous Blessings (Outro)",
            "featuring":[],
            "writers": [],
            "producers":[],
            "length": "0:39",
            }
        ]
    },
    "unknown":{
        "unknow": "unknown"
    }
}

app.get('/', (request, response) => {
    response.sendFile(__dirname + '/index.html')
})

app.get('/api/:name', (request, response) => {
    const albumName = request.params.name.toLowerCase()
    if(albums[albumName]){
        response.json(albums[albumName])
    }else{
        response.json(albums["unknown"])
    }
})

app.listen(process.env.PORT || PORT, () => {
    console.log(`Server running on port ${PORT}`)
})